### ISSUE TITLE
Feature request: Add vterm support

### ISSUE THREAD

**Issue by sanngridhr** [crmsnbleyd/flexoki-emacs-theme#3]
I don't consider myself fluent enough in emacs themes to do it myself properly, but [here](https://github.com/doomemacs/themes/blob/ae18b84e01496c4ebd572cad00a89516af089a94/doom-themes-base.el#L234) is Doom's implementation, if this is helful.

**Comment by crmsnbleyd** [comment]
Thanks for the feature request!  I believe https://github.com/crmsnbleyd/flexoki-emacs-theme/commit/156843cbb4b87fc2fa2d6a13269b3226394b1802 should do what you want. The implementation was indeed helpful.

**Comment by sanngridhr** [comment]
Thanks for feature addition!
